export const weekNames = [
  "Week 1 — Everyday Life & Opinion",
  "Week 2 — Ideas & Concepts",
  "Week 3 — Society & Culture",
  "Week 4 — Personal Growth & Mindset",
  "Week 5 — Communication & Language",
  "Week 6 — Observation & The Physical World",
  "Week 7 — Knowledge & Thinking",
  "Week 8 — Relationships & Others",
  "Final — The Big Questions",
];

export const topics = [
  { cat: "Opinion",      topic: "Paper books vs digital books",                              prompt: "Beyond nostalgia — what are the real differences in how we read, remember, and relate to a book?",         mode: "P" },
  { cat: "Reflection",   topic: "The best time of day to think deeply",                      prompt: "When is your mind sharpest? What conditions actually produce your best thinking?",                          mode: "I" },
  { cat: "Observation",  topic: "Something you noticed today that most people overlook",     prompt: "Pick one specific thing. Why do you think it goes unnoticed?",                                             mode: "I" },
  { cat: "Personal",     topic: "How you prefer to receive feedback",                        prompt: "What makes feedback useful versus harmful? What's your honest reaction to criticism?",                      mode: "E" },
  { cat: "Mindset",      topic: "The value of being bored",                                  prompt: "What happens in your mind when you resist filling silence? Is boredom a problem or a resource?",           mode: "P" },
  { cat: "Lifestyle",    topic: "Morning routines — discipline or overrated?",               prompt: "Are structured mornings a genuine advantage or a form of self-performance?",                               mode: "P" },
  { cat: "Self",         topic: "A habit you have that you've never examined",               prompt: "Pick one automatic behavior. Where did it come from and what does it actually do for you?",                mode: "E" },
  { cat: "Psychology",   topic: "What is confidence really?",                                prompt: "Not the performance of confidence — the actual state. What does it feel like and where does it come from?", mode: "E" },
  { cat: "Productivity", topic: "The difference between being busy and being productive",    prompt: "They feel similar from the inside. How do you tell them apart?",                                           mode: "I" },
  { cat: "Values",       topic: "What success means to you personally",                      prompt: "Not what you were taught it means — what you actually measure it by, honestly.",                           mode: "E" },
  { cat: "Psychology",   topic: "Why people resist change even when they want it",           prompt: "You've seen this in yourself. What's the real mechanism?",                                                  mode: "I" },
  { cat: "Philosophy",   topic: "The role of luck vs effort in outcomes",                    prompt: "Where does credit honestly belong? Does your answer change when things go badly?",                         mode: "P" },
  { cat: "Learning",     topic: "What it means to be well-read",                             prompt: "Is it breadth, depth, retention, or something else? Can you be well-read in one domain?",                  mode: "I" },
  { cat: "Cognition",    topic: "Why humans find patterns everywhere",                       prompt: "Useful feature or dangerous bug? Where has it helped or misled you?",                                      mode: "I" },
  { cat: "Society",      topic: "What social media has done to conversation",                prompt: "Not the standard take — your specific observation about how discourse has actually changed.",               mode: "P" },
  { cat: "Relationships",topic: "The value of disagreement in a friendship",                 prompt: "When does friction make a relationship stronger? When does it break it?",                                   mode: "E" },
  { cat: "Memory",       topic: "Why nostalgia is so powerful",                              prompt: "What does it actually do to your thinking? Is it honest or does it edit?",                                 mode: "E" },
  { cat: "Society",      topic: "Are manners a form of honesty or performance?",             prompt: "When you're polite, are you being genuine or wearing a mask — and does it matter?",                        mode: "P" },
  { cat: "Culture",      topic: "What gets lost when a language disappears",                 prompt: "Language carries culture, memory, and ways of thinking. What exactly dies with it?",                       mode: "I" },
  { cat: "Society",      topic: "Why people follow trends they don't understand",            prompt: "Fashion, slang, ideas — why do we adopt things we can't fully explain?",                                   mode: "E" },
  { cat: "Culture",      topic: "The idea of home",                                          prompt: "Is home a place, a feeling, or a set of people? Can you have more than one?",                              mode: "E" },
  { cat: "Mindset",      topic: "The most useful thing failure has taught you",              prompt: "Not a cliché — a specific, real lesson. How did it change your behavior?",                                 mode: "E" },
  { cat: "Growth",       topic: "When is perseverance actually stubbornness?",               prompt: "How do you know the difference between commitment and being too proud to quit?",                           mode: "P" },
  { cat: "Mindset",      topic: "How you handle uncertainty",                                prompt: "Do you tolerate it, resist it, seek it? What's your honest relationship with not knowing?",                mode: "E" },
  { cat: "Growth",       topic: "A belief you've changed your mind about",                   prompt: "What used to feel obviously true that you now see differently? What shifted you?",                         mode: "E" },
  { cat: "Mindset",      topic: "The difference between motivation and discipline",          prompt: "One is a feeling, one is a system. Which do you rely on, and which should you?",                           mode: "P" },
  { cat: "Growth",       topic: "What you'd tell your 15-year-old self",                     prompt: "One piece of advice — not comfort, but genuinely useful insight.",                                         mode: "I" },
  { cat: "Mindset",      topic: "How you know when you're making a decision from fear",      prompt: "What does fear-based thinking look like in your own patterns?",                                            mode: "E" },
  { cat: "Communication",topic: "The difference between being heard and being understood",   prompt: "Can you be heard by everyone and understood by no one? When does this happen?",                            mode: "I" },
  { cat: "Language",     topic: "Why some ideas are nearly impossible to explain",           prompt: "Pick a feeling or concept you struggle to put into words. Why is that?",                                   mode: "E" },
  { cat: "Communication",topic: "What silence communicates that words cannot",               prompt: "When does not speaking say more than speaking?",                                                            mode: "I" },
  { cat: "Language",     topic: "Why metaphors are more powerful than data",                 prompt: "A good metaphor can change minds where numbers don't. Why?",                                               mode: "P" },
  { cat: "Ethics",       topic: "The ethics of persuasion",                                  prompt: "When does persuasion become manipulation? Is there a clear line?",                                         mode: "P" },
  { cat: "Language",     topic: "Words you use too much and what that reveals",              prompt: "Pick a filler word or overused phrase you default to. What does it signal?",                               mode: "I" },
  { cat: "Communication",topic: "What makes someone a compelling storyteller",               prompt: "Not fiction — in real life. What do the best storytellers actually do?",                                   mode: "I" },
  { cat: "Observation",  topic: "A texture, sound, or smell that transports you instantly",  prompt: "Pick one sensory detail. Where does it take you? Why does it stick?",                                      mode: "I" },
  { cat: "Reflection",   topic: "What you spend the most mental energy on daily",            prompt: "If you tracked your thoughts for 24 hours, what category would dominate?",                                 mode: "E" },
  { cat: "Observation",  topic: "How a city or neighborhood reflects its people",            prompt: "Pick a place you know. What does its design say about the people who built it?",                           mode: "I" },
  { cat: "Reflection",   topic: "The last thing that genuinely surprised you",               prompt: "Real surprise — something that revised your model of the world.",                                          mode: "E" },
  { cat: "Observation",  topic: "What drives you to do something without being asked",       prompt: "Find the intrinsic motivation beneath the behavior. What is it really?",                                  mode: "E" },
  { cat: "Reflection",   topic: "A place where you feel most like yourself",                 prompt: "What about that environment frees you? What does that tell you about what you need?",                      mode: "E" },
  { cat: "Observation",  topic: "Something you do differently from most people around you",  prompt: "Not better or worse — just different. Where did that divergence come from?",                              mode: "P" },
  { cat: "Epistemology", topic: "How do you know when you actually understand something?",   prompt: "Can you explain it simply? Can you apply it? What's your test for real understanding?",                   mode: "I" },
  { cat: "Thinking",     topic: "The limits of logic",                                       prompt: "Are there questions that reason alone can't answer? What fills the gap?",                                  mode: "E" },
  { cat: "Knowledge",    topic: "What it means to be an expert",                             prompt: "Is expertise about years spent, depth of knowledge, or something else entirely?",                         mode: "I" },
  { cat: "Thinking",     topic: "Why we're often wrong about what will make us happy",       prompt: "Where do your predictions go wrong?",                                                                      mode: "E" },
  { cat: "Epistemology", topic: "The value of not having an opinion",                        prompt: "When is 'I don't know' a sign of wisdom rather than weakness?",                                           mode: "I" },
  { cat: "Knowledge",    topic: "What curiosity actually feels like from the inside",        prompt: "Describe the state. Is it comfortable? Uncomfortable? What triggers it for you?",                         mode: "E" },
  { cat: "Thinking",     topic: "The most dangerous assumption you carry",                   prompt: "One belief you hold so automatically it doesn't feel like a belief.",                                      mode: "E" },
  { cat: "Relationships",topic: "What makes someone trustworthy",                            prompt: "Not just reliable — trustworthy. What's the difference and what earns it?",                               mode: "P" },
  { cat: "Relationships",topic: "How you know when a conversation is genuinely good",        prompt: "What distinguishes a conversation you remember from one you immediately forget?",                          mode: "I" },
  { cat: "Relationships",topic: "The difference between giving advice and actually helping", prompt: "When does advice make things worse?",                                                                      mode: "I" },
  { cat: "Others",       topic: "Why we judge people for the same things we do ourselves",   prompt: "Hypocrisy is universal. What's the psychological mechanism?",                                             mode: "P" },
  { cat: "Relationships",topic: "What loyalty actually demands",                             prompt: "Is loyalty always a virtue? When does it require honesty over support?",                                  mode: "P" },
  { cat: "Others",       topic: "The kind of person you find hardest to understand",         prompt: "An archetype, not an individual. What makes them difficult to relate to?",                                mode: "E" },
  { cat: "Relationships",topic: "What you've learned about yourself from your friendships",  prompt: "Patterns, tendencies, things you only see reflected in others.",                                          mode: "E" },
  { cat: "Big Picture",  topic: "What is a life well-spent?",                                prompt: "Not a perfect life — a well-spent one. What does it look like at the end?",                               mode: "E" },
  { cat: "Big Picture",  topic: "The thing you most want to be remembered for",              prompt: "Be honest, not noble. What do you actually want?",                                                         mode: "P" },
  { cat: "Big Picture",  topic: "What 'progress' really means to you",                       prompt: "Personal, societal, or both? How do you measure it?",                                                      mode: "I" },
  { cat: "Reflection",   topic: "What this 60-day challenge taught you about yourself",      prompt: "Look back. What patterns emerged? What surprised you?",                                                    mode: "E" },
];

export const modeCfg = {
  P: {
    label: "PERSUADE",
    what: "Make a case. Argue for something. Change minds.",
    tips: [
      { icon: "→", text: "State your position clearly in the first paragraph" },
      { icon: "→", text: "Acknowledge the opposing view before rebutting it" },
      { icon: "→", text: "Close with what you want the reader to do or believe" },
    ],
    writeDesc: "Argue for a clear position. Use evidence, address counterarguments, and close with conviction.",
    speakDesc: "Deliver your argument as if you need to actually convince someone in the room.",
  },
  I: {
    label: "INFORM",
    what: "Illuminate. Explain. Help the reader understand something clearly.",
    tips: [
      { icon: "→", text: "Choose a clear angle — not everything about the topic" },
      { icon: "→", text: "Use a concrete example for every abstract claim" },
      { icon: "→", text: "End with the single most important thing to remember" },
    ],
    writeDesc: "Explain clearly. Prioritise the reader's understanding over your own comfort with the material.",
    speakDesc: "Deliver it as if the person listening has never thought about this before.",
  },
  E: {
    label: "EXPLORE",
    what: "Think out loud. No thesis required — just honest inquiry.",
    tips: [
      { icon: "→", text: "Start with a genuine question, not an answer" },
      { icon: "→", text: "Change direction if something unexpected surfaces" },
      { icon: "→", text: "End with where your thinking landed, even if unresolved" },
    ],
    writeDesc: "Follow your thinking wherever it leads. Structure can be loose — honesty is the priority.",
    speakDesc: "Speak as if you're thinking through it live. Uncertainty is fine here.",
  },
};
